-- =====================================================
-- Room Ready Supply — Product Seed
-- Paste this entire script into:
--   Supabase Dashboard → SQL Editor → New Query → Run
-- =====================================================

INSERT INTO products (name, slug, sku, category_name, description, price, sale_price, is_on_sale, unit, case_qty, pack_size, image_url, is_featured, is_active, updated_at)
VALUES
('Pure Bright® Germicidal Ultra Bleach','pure-bright-germicidal-ultra-bleach','11008635042','Cleaning Chemicals','Germicidal Ultra Bleach — EPA registered disinfectant and sanitizer with kill claims on 50+ pathogens including C. Difficile Spore. 6% Sodium Hypochlorite.',35.30,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/pure-bright-germicidal-ultra-bleach.jpg',false,true,NOW()),
('Professional Lysol® Disinfectant Spray','professional-lysol-disinfectant-spray','74828','Cleaning Chemicals','Aerosol Crisp Linen® — Kills cold and flu viruses, mold allergens, and odor-causing bacteria. Hospital-grade germicidal spray.',123.05,NULL,false,'Case',12,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/professional-lysol-disinfectant-spray.jpg',false,true,NOW()),
('Clorox® Healthcare® Bleach Germicidal Cleaner','clorox-healthcare-bleach-germicidal-cleaner','68970','Cleaning Chemicals','Bleach Germicidal Cleaner — Kills C. Difficile and C. auris in 3 minutes. One-step cleaner, disinfectant and deodorizer.',97.45,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/clorox-healthcare-bleach-germicidal-cleaner.jpg',false,true,NOW()),
('CloroxPro™ Clorox® Disinfecting Wipes','cloroxpro-clorox-disinfecting-wipes','31547','Cleaning Chemicals','Fresh Scent — Kills 99.9% of germs. EPA approved for SARS-CoV-2. Bleach-free. Sanitizes in as little as 10 seconds.',0,NULL,false,'Each',1,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/cloroxprotm-clorox-disinfecting-wipes.jpg',false,true,NOW()),
('Sani Professional® Disinfecting Multi-Surface Wipe','sani-professional-disinfecting-multi-surface-wipe','P22884','Cleaning Chemicals','Canister — Kills 99.9% of bacteria in 15 seconds. Effective against 26 organisms. Alcohol and bleach free. Moisture-lock lid.',0,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/sani-professional-disinfecting-multi-surface-wipe.jpg',false,true,NOW()),
('Champion Sprayon® Vista Cleer™ Glass Cleaner','champion-sprayon-vista-cleer-glass-cleaner','438-5155','Cleaning Chemicals','Glass Cleaner — Foaming formula clings to vertical surfaces. No ammonia, alcohol, silicone or abrasives. Streak-free fast drying.',0,NULL,false,'Case',12,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/champion-sprayon-vista-cleertm-glass-cleaner.jpg',false,true,NOW()),
('Performance Plus™ Foaming Glass Cleaner','performance-plus-foaming-glass-cleaner','P050','Cleaning Chemicals','Foaming Glass Cleaner — Cleans and polishes windows and mirrors. Long-lasting vertical cling. No ammonia, no rinsing required.',0,NULL,false,'Case',12,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/performance-plustm-foaming-glass-cleaner.jpg',false,true,NOW()),
('Windex® Glass Indoor Blue Liquid Refill','windex-glass-indoor-blue-liquid-refill','316147','Cleaning Chemicals','America''s #1 glass cleaner. Streak-free shine on glass, mirrors, and more. Convenient bulk refill format.',0,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/windex-glass-indoor-blue-liquid-refill.jpg',false,true,NOW()),
('Windex® Original w/Trigger Sprayer','windex-original-w-trigger-sprayer','313042','Cleaning Chemicals','Ready-to-use trigger sprayer. Trusted streak-free shine on windows, mirrors and hard surfaces. Fast drying formula.',0,NULL,false,'Case',8,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/windex-original-w-trigger-sprayer.jpg',false,true,NOW()),
('CloroxPro™ Pine-Sol® Multi-Surface Cleaner','cloroxpro-pine-sol-multi-surface-cleaner','60607','Cleaning Chemicals','Lemon Fresh — Cleans, deodorizes and disinfects in one step. Kills 99.9% of germs. 2X concentrated, makes up to 80 gallons.',47.60,NULL,false,'Case',3,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/cloroxprotm-pine-sol-multi-surface-cleaner.jpg',false,true,NOW()),
('Performance Plus™ Low Suds Powder Laundry Detergent','performance-plus-low-suds-powder-laundry-detergent','PP40PAIL','Laundry Supplies','Heavy-duty powder laundry detergent. HE and standard machine compatible. Effective in hot, warm and cold water cycles.',0,NULL,false,'Each',1,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/performance-plustm-low-suds-powder-laundry-detergent.jpg',false,true,NOW()),
('Purex® Mountain Breeze® Liquid Laundry Detergent','purex-mountain-breeze-liquid-laundry-detergent','5016','Laundry Supplies','Mountain Breeze® liquid detergent with Dirt Lift Action™. 115 loads. Removes ground-in dirt and stains from fabric fibers.',0,NULL,false,'Case',4,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/purex-mountain-breeze-liquid-laundry-detergent.jpg',false,true,NOW()),
('FINISH® Powerball® Deep Clean Dishwashing Tabs','finish-powerball-deep-clean-dishwashing-tabs','97330','Dishwashing Supplies','Deep Clean Tabs with Pre-soaking Powerball. Cuts through grease, breaks down stains. Oxygen-based bleach. Fresh scent.',113.65,NULL,false,'Case',4,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/finish-powerball-deep-clean-dishwashing-tabs.jpg',false,true,NOW()),
('Dawn® Professional Manual Pot & Pan Detergent','dawn-professional-manual-pot-pan-detergent','70681','Dishwashing Supplies','Original Scent — Cuts 100% of commercial grease. 2X longer-lasting suds. Fill up to 512 sinks per case. For commercial kitchens.',138.85,NULL,false,'Each',1,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/dawn-professional-manual-pot-and-pan-detergent-dish-soap.jpg',false,true,NOW()),
('Performance Plus™ Low Density Can Liners','performance-plus-low-density-can-liners','PL385815B','Trash Liners','Black 1.5 EQ mil — Superior stretch resistance, minimizes punctures and tears. Interleaved rolls. 38 x 58 size.',37.95,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/performance-plustm-low-density-can-liners.jpg',false,true,NOW()),
('Inteplast HDPE Institutional Trash Can Liners','inteplast-hdpe-institutional-trash-can-liners','S243308N','Trash Liners','Natural 8 mic — For paper and non-sharp objects. Excellent puncture resistance. Star seal bottom. Compact coreless rolls. 24 x 33.',50.05,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/inteplast-hdpe-institutional-trash-can-liners.jpg',false,true,NOW()),
('NAPCO Black Heavy Duty Municipal Liners','napco-black-heavy-duty-municipal-liners','RM3858H','Trash Liners','1.5N-H — Heaviest true gauge recycled can liners. Star seal bottom. Municipal-grade durability. Coreless rolls. 38 x 58.',40.25,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/napco-black-heavy-duty-municipal-liners.jpg',false,true,NOW()),
('NOVA® Black Repro Coreless Can Liners 1.2 mil 38x58','nova-black-repro-coreless-can-liners-12-mil-38x58','NOVA519','Trash Liners','Black 1.2 mil — Up to 70% recycled content. Economical and environmentally conscious. 38 x 58 size.',39.45,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-black-repro-coreless-can-liners.jpg',false,true,NOW()),
('NOVA® Black Repro Coreless Can Liners 1.6 mil 38x58','nova-black-repro-coreless-can-liners-16-mil-38x58','NOVA523','Trash Liners','Black 1.6 mil — Up to 70% recycled content. Heavy-duty economical liner. 38 x 58 size.',52.45,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-black-repro-coreless-can-liners.jpg',false,true,NOW()),
('NOVA® Black Repro Coreless Can Liners 1.2 mil 40x46','nova-black-repro-coreless-can-liners-12-mil-40x46','NOVA517','Trash Liners','Black 1.2 mil — Up to 70% recycled content. Economical and environmentally conscious. 40 x 46 size.',33.00,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-black-repro-coreless-can-liners.jpg',false,true,NOW()),
('NOVA® Black Repro Coreless Can Liners 1.6 mil 43x47','nova-black-repro-coreless-can-liners-16-mil-43x47','NOVA522','Trash Liners','Black 1.6 mil — Up to 70% recycled content. Heavy-duty 43 x 47 size for larger containers.',48.15,NULL,false,'Case',100,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-black-repro-coreless-can-liners.jpg',false,true,NOW()),
('Green® Heritage Pro 2-Ply Bathroom Tissue 500 Sheets','green-heritage-pro-2-ply-bathroom-tissue-500','276','Toilet Paper','500 Sheets/Roll — SFI® Certified. Fast Flush® septic-safe. Soft 2-ply white tissue. Sustainable paper solution.',54.45,NULL,false,'Case',96,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/green-heritage-pro-2-ply-bathroom-tissue.jpg',false,true,NOW()),
('Green® Heritage Pro 2-Ply Bathroom Tissue 400 Sheets','green-heritage-pro-2-ply-bathroom-tissue-400','248','Toilet Paper','400 Sheets/Roll — SFI® Certified. Fast Flush® septic-safe. Soft 2-ply white tissue. Sustainable paper solution.',61.05,NULL,false,'Case',96,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/green-heritage-pro-2-ply-bathroom-tissue.jpg',false,true,NOW()),
('Empress™ 2 Ply Facial Tissue Cube Box','empress-2-ply-facial-tissue-cube-box','FT 30852','Guest Room Supplies','Cube Box — Soft and gentle 2-ply facial tissue. Perfect for home, office, or on-the-go. 85 ct. per box.',0,NULL,false,'Case',36,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-2-ply-facial-tissue.jpg',false,true,NOW()),
('Empress™ Virgin 2 Ply Facial Tissue Box','empress-virgin-2-ply-facial-tissue-box','FT 301002','Guest Room Supplies','Box — Premium virgin fiber, soft and gentle. Bright white appearance. 100 ct. per box.',0,NULL,false,'Case',30,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-virgin-2-ply-facial-tissue.jpg',false,true,NOW()),
('Livi® VPG® Select Cube Box Facial Tissue','livi-vpg-select-cube-box-facial-tissue','11516','Guest Room Supplies','2 Ply — Luxurious softness from sustainable virgin-grown fiber. Naturally whiter and brighter. 90 ct. cube box.',0,NULL,false,'Case',36,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/livi-vpg-select-cube-box-facial-tissue.jpg',false,true,NOW()),
('Livi® VPG® Select Flat Box Facial Tissue','livi-vpg-select-flat-box-facial-tissue','11513','Guest Room Supplies','2 Ply — Luxurious softness from sustainable virgin-grown fiber. Naturally whiter and brighter. 100 sheet flat box.',0,NULL,false,'Case',30,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/livi-vpg-select-flat-box-facial-tissue.jpg',false,true,NOW()),
('Empress™ 2-Ply Center Pull Virgin Towel','empress-2-ply-center-pull-virgin-towel','CP 660010','Paper Towels','White 2 Ply — One-handed dispensing convenience. Fast water absorption. Virgin fiber quality. Commercial restroom ready.',0,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-2-ply-center-pull-virgin-towel.jpg',false,true,NOW()),
('Sofidel Double Layer Center Pull Towel','sofidel-double-layer-center-pull-towel','410081','Paper Towels','White — Double-layer embossed virgin pulp. 600 towels per roll. Reliable absorbency and performance.',0,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/sofidel-double-layer-center-pull-towel.jpg',false,true,NOW()),
('Green® Heritage Pro Kitchen Roll Towel','green-heritage-pro-kitchen-roll-towel','585','Paper Towels','2 Ply — SFI® Certified. Strong absorbent performance. Sustainable kitchen roll with softness and visual appeal.',0,NULL,false,'Case',30,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/green-heritage-pro-kitchen-roll-towel.jpg',false,true,NOW()),
('NOVA® 2 Ply Kitchen Roll Towel','nova-2-ply-kitchen-roll-towel','NOVA 3085','Paper Towels','Roll White — Versatile and durable. Strong two-ply design handles spills while remaining gentle on surfaces.',0,NULL,false,'Case',30,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-2-ply-kitchen-roll-towel.jpg',false,true,NOW()),
('Morcon® Morsoft® Multifold Towel Kraft','morcon-morsoft-multifold-towel-kraft','R720','Paper Towels','Kraft — Fits standard multifold dispensers. EPA-compliant post-consumer content. Economical for commercial restrooms.',0,NULL,false,'Case',4000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/morcon-morsoft-multifold-towel.jpg',false,true,NOW()),
('Morcon® Valay® Multifold Towel White','morcon-valay-multifold-towel-white','VT1106','Paper Towels','White — Universal dispenser compatibility. EPA-compliant. Reliable drying for high-traffic restrooms and restaurants.',0,NULL,false,'Case',4000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/morcon-valay-multifold-towel.jpg',false,true,NOW()),
('NOVA® Hardwound Towel Kraft 8x350','nova-hardwound-towel-kraft-8x350','NOVA 350N','Paper Towels','Kraft — High-capacity roll for high-traffic areas. Reliable absorbency. Efficient dispensing system. 8" x 350''.',32.90,NULL,false,'Case',12,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-hardwound-towel.jpg',false,true,NOW()),
('NOVA® Hardwound Towel Kraft 8x800','nova-hardwound-towel-kraft-8x800','NOVA 800N','Paper Towels','Kraft — High-capacity roll for high-traffic areas. Reliable absorbency. Efficient dispensing system. 8" x 800''.',42.05,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-hardwound-towel.jpg',false,true,NOW()),
('NOVA® Hardwound Towel White 8x350','nova-hardwound-towel-white-8x350','NOVA 350W','Paper Towels','White — High-capacity roll for high-traffic areas. Reliable absorbency. Efficient dispensing system. 8" x 350''.',35.75,NULL,false,'Case',12,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-hardwound-towel.jpg',false,true,NOW()),
('NOVA® Hardwound Towel White 8x800','nova-hardwound-towel-white-8x800','NOVA 800W','Paper Towels','White — High-capacity roll for high-traffic areas. Reliable absorbency. Efficient dispensing system. 8" x 800''.',43.85,NULL,false,'Case',6,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/nova-hardwound-towel.jpg',false,true,NOW()),
('Empress™ Blue Nitrile Powder Free Gloves Small','empress-blue-nitrile-powder-free-gloves-small','ENPFS2001','Facility Supplies','Small Blue — Powder-free. Excellent tactile sensitivity. Suitable for medical, laboratory and food handling applications.',43.45,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Blue Nitrile Powder Free Gloves Medium','empress-blue-nitrile-powder-free-gloves-medium','ENPFM2002','Facility Supplies','Medium Blue — Powder-free. Excellent tactile sensitivity. Suitable for medical, laboratory and food handling applications.',43.45,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Blue Nitrile Powder Free Gloves Large','empress-blue-nitrile-powder-free-gloves-large','ENPFL2003','Facility Supplies','Large Blue — Powder-free. Excellent tactile sensitivity. Suitable for medical, laboratory and food handling applications.',43.45,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Blue Nitrile Powder Free Gloves XL','empress-blue-nitrile-powder-free-gloves-xl','ENPFXL2004','Facility Supplies','XL Blue — Powder-free. Excellent tactile sensitivity. Suitable for medical, laboratory and food handling applications.',43.45,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Exam Grade Blue Nitrile Gloves Small','empress-exam-grade-blue-nitrile-gloves-small','ENES2001','Facility Supplies','Small Blue — Exam-grade protection. Powder-free. Chemical and puncture resistant. Meets stringent medical standards.',45.20,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-exam-grade-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Exam Grade Blue Nitrile Gloves Medium','empress-exam-grade-blue-nitrile-gloves-medium','ENEM2002','Facility Supplies','Medium Blue — Exam-grade protection. Powder-free. Chemical and puncture resistant. Meets stringent medical standards.',45.20,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-exam-grade-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Exam Grade Blue Nitrile Gloves Large','empress-exam-grade-blue-nitrile-gloves-large','ENEL2003','Facility Supplies','Large Blue — Exam-grade protection. Powder-free. Chemical and puncture resistant. Meets stringent medical standards.',45.20,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-exam-grade-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Empress™ Exam Grade Blue Nitrile Gloves XL','empress-exam-grade-blue-nitrile-gloves-xl','ENEXL2004','Facility Supplies','XL Blue — Exam-grade protection. Powder-free. Chemical and puncture resistant. Meets stringent medical standards.',45.20,NULL,false,'Case',1000,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/empresstm-exam-grade-blue-nitrile-powder-free-gloves.jpg',false,true,NOW()),
('Dial® Gold Antimicrobial Liquid Hand Soap','dial-gold-antimicrobial-liquid-hand-soap','88047','Hand Soap','Antimicrobial Liquid Hand Soap — Kills 99.9% of germs. Dermatologist-tested. Gentle formula for frequent handwashing.',0,NULL,false,'Case',4,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/dial-gold-antimicrobial-liquid-hand-soap.jpg',false,true,NOW()),
('Performance Plus™ White Lotion Skin Cleanser','performance-plus-white-lotion-skin-cleanser','PP-28130','Hand Soap','White Lotion Skin Cleanser — Mild detergents and emollients. Leaves skin soft and smooth. Pleasant almond fragrance.',0,NULL,false,'Case',4,1,'https://res.cloudinary.com/ddx3g4yse/image/upload/performance-plustm-white-lotion-skin-cleanser.jpg',false,true,NOW())
ON CONFLICT (slug) DO UPDATE SET
  name          = EXCLUDED.name,
  sku           = EXCLUDED.sku,
  category_name = EXCLUDED.category_name,
  description   = EXCLUDED.description,
  price         = EXCLUDED.price,
  unit          = EXCLUDED.unit,
  case_qty      = EXCLUDED.case_qty,
  image_url     = EXCLUDED.image_url,
  is_active     = EXCLUDED.is_active,
  updated_at    = NOW();

-- Create inventory records for all products (default: in_stock, qty 100)
INSERT INTO inventory (product_id, stock_qty, status, updated_at)
SELECT id, 100, 'in_stock', NOW()
FROM products
ON CONFLICT (product_id) DO NOTHING;

SELECT COUNT(*) AS products_total FROM products;
SELECT COUNT(*) AS inventory_total FROM inventory;
